### ISSUE TITLE
Release code and datasets

### ISSUE THREAD

**Issue by rtanaka-lab** [herobd/dessurt#1]
Hi, 

Thank you for sharing interesting paper. I was wondering if there is an expected date on when you will be releasing your code and datasets for pre-training Dessurt.

**Comment by herobd** [comment]
I don't have a date yet. The majority of the authors want to wait until the paper is accepted to a conference before releasing the code. It's submitted to ECCV which has it's final decisions in July.

**Comment by herobd** [comment]
Ok, it's released now. The paper was rejected from ECCV, but we resubmitted it to TiE, a workshop at ECCV.
