### ISSUE TITLE
ITT-CDIP annotation

### ISSUE THREAD

**Issue by Mohamed-Dhouib** [herobd/dessurt#3]
Hey, Thanks for the great work and for open sourcing it !
I was trying to use your IIT-CDIP-annotations for pre-traning my own model for research purposes. But the annotations that you provided don't cover all the dataset. Is this intended ?
Thanks !

**Comment by herobd** [comment]
Sorry, I just had never finished doing it. I trained my model with the finished subset.

**Comment by Mohamed-Dhouib** [comment]
Ok thanks for your answer !
