### ISSUE TITLE
Missing metadata in DocVQA validation/evaluation process

### ISSUE THREAD

**Issue by ChristopherCho** [herobd/dessurt#5]
Hi, thanks for releasing your great work!
By the way, I'm currently having trouble with training and evaluating on official DocVQA dataset.
Here's the error message I got.

```
start valid loop
Traceback (most recent call last):
  File "train.py", line 236, in <module>
    main(None,config, args.resume)
  File "train.py", line 138, in main
    trainer.train()
  File "/root/dessurt/base/base_trainer.py", line 428, in train
    val_result = self._valid_epoch()
  File "/root/dessurt/trainer/qa_trainer.py", line 259, in _valid_epoch
    losses,log_run, out = self.run(instance,valid=True)
  File "/root/dessurt/trainer/qa_trainer.py", line 693, in run
    assert len(b_metadata['all_answers'])==1
TypeError: 'NoneType' object is not subscriptable
```

From debugging, I found that metadata is missing in DocVQA dataset.
After I fixed the following codeline, I could finally evaluate the model with official DocVQA dataset

https://github.com/herobd/dessurt/blob/662fbcb0962603e7f514ff5b1258185e6c7fb7e2/data_sets/docvqa.py#L57
=>
```
        return None,None,None,form_metadata,qa
```

Could you confirm that this modification is that the code originally intended?
Thank you! :)

**Comment by herobd** [comment]
Yes, thank you. I must have introduced that in some refactoring. Thanks for catching it. I'll fix it in the repo

**Comment by ChristopherCho** [comment]
Thank you for your quick response and update! :)
As the code is updated, I'll close this issue.
