### ISSUE TITLE
Colab Demo

### ISSUE THREAD

**Issue by sandorkonya** [herobd/dessurt#6]
Thank you for publishing this work!
The effort you did for the creation of the synthetic dataset is really great!

I tried to run the colab demo - 
"Running Dessurt fine-tuned on DocVQA interactively: https://colab.research.google.com/drive/1rvjBv70Cguigp5Egay6VnuO-ZYgu24Ax?usp=sharing"

There is an error downloading the file with gdown, tried with
!gdown --fuzzy "https://drive.google.com/file/d/1Lj6xMvQcF9dSCxVQS2nia4SiEoPXbtCv/view?usp=sharing" -O dessurt_docvqa_best.pth

but i get following error:

Access denied with the following error:
 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 
You may still be able to access the file from the browser:

Could you possibly change the permission of the weihts? Downloading and reuploading it to Colab take excrutiatingly long time...

thank you!

**Comment by herobd** [comment]
It is actually not a permission issue. Google is preventing gdown from downloading it because too many people have accessed it. I didn't know they would do this when I initially set it up.
A faster way may be to add the file to your drive and then mount it to the colab.
Sorry.

**Comment by sandorkonya** [comment]
Hi,

oh, i did not know this either. Surely, i will try that way!

thank you anyway!
