### ISSUE TITLE
Inference and training are really slow

### ISSUE THREAD

**Issue by Mohamed-Dhouib** [herobd/dessurt#7]
Hello,
I just finished comparing Dessurt to Donut using various datasets.
Dessurt shows better performances but it is much slower than Donut.
Is it normale or did I miss something ?
For inference I use this code :  `output=net(image,[['mytasktoken']],RUN=True)`. Where net is an instance of Dessurt.
Thanks in advance !

**Comment by herobd** [comment]
Are you running on GPU or CPU?

**Comment by Mohamed-Dhouib** [comment]
Both, sorry I wasn't clear, I'm speaking about the difference between inference time of dessurt compared donut. Like dessurt is four times slower with my expriments. You use caching right (That what I unsterdood from the code). 
(Got 1.2 sec on a RTX 6000 GPU on Sroie with the same config as the pretraining)

**Comment by herobd** [comment]
Are you using the Donut huggingface implementation? My guess is their code is far more optimized than mine. Other than implementing the caching I didn't do much to optimize mine. Additionally, I have cross attention that isn't present in Donut, which probably makes mine slower.

**Comment by Mohamed-Dhouib** [comment]
Yes my guess was also that the cross attention, the large attention windows and that a big part of the compute is done on a large number of visual token compared to a Swin transformer slowed things down ! Thanks for your answer and great work by the way!
